---
title: "Spatial Viz"
# execute:
#   warning: false
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
#Spa-Viz
```{r Spa-viz}
#| fig-cap: "The commonwealth counties"
#| fig-alt: "It shows that the member of commonwealth countries,from https://github.com/rfordatascience/tidytuesday/blob/main/data/2024/2024-11-05/readme.md"
library(tidyverse)

# Data 
democracy_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-11-05/democracy_data.csv')

```

```{r}
# Commonwealth 

commonwealth <- democracy_data |>
  filter(is_commonwealth == TRUE)

commonwealth |>
  group_by(country_name) 

```
```{r}
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(sf)


world <- ne_countries(scale = "medium", returnclass = "sf")


commonwealth_1950 <- commonwealth |>
  filter(year == 1950)

world <- world |>
  mutate(is_commonwealth = name %in% commonwealth_1950$country_name)

ggplot(data = world) +
  geom_sf(aes(fill = is_commonwealth), color = "blue") +
  scale_fill_manual(values = c("TRUE" = "red", "FALSE" = "grey90")) +
  theme_minimal() +
  labs(title = "Commonwealth Countries in 1950", fill = "Commonwealth")
```
  


