---
title: "soloproject"
format: html
---
```{r}
#| fig-cap: "The econic develop situation in China"
library(tidyverse)
library(tidyr)
library(dplyr)
library(sf)
world_shapes<-read_sf("../dataverse_files/province.shp")
China_gdp<-read.csv("../dataverse_files/China-gdp.csv")
China_gdp_2020 <- China_gdp |>
  filter(X == 2020)
world_shapes<-world_shapes |>
  mutate(province_clean = gsub("( Sheng| Shi| Zizhiqu)", "", NAME_PINGY))


gdp_long <- China_gdp_2020 |>
  pivot_longer(
    cols = -X,        
    names_to = "province",
    values_to = "gdp")

gdp_long <- world_shapes |>
  left_join(gdp_long, by = c("province_clean" = "province"))

ggplot(data=gdp_long)+
  geom_sf(aes(fill = gdp), color = "white") +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  theme_void() +
  labs(title = "2020 China GDP for 100 millions yuan based on province", fill ="", caption = "source: https://www.kaggle.com/datasets/concyclics/chinas-gdp-in-province madeby: Xi Fang")

```

The economic development of China shows a great imblance between different provinces.In the chart, we can see that Jiangsu and Guangdong provinces have gdp far exceeding that of other provinces. This is inseparable from two important reasons: one is the geographical advantage, and the other is their proximity to a developed economic center. First, take Guangdong Province as an example. Its proximity to the intersection of the Indian Ocean and the Pacific Ocean has brought about a huge amount of shipping, promoting economic development. At the same time, its proximity to Hong Kong, a developed economic and trade city, provides more opportunities. Jiangsu, on the other hand, has ensured sufficient Commodity Exchange through trade with Japan, South Korea and the Pacific Ocean, which has vigorously developed an ocean-centered economy. However, in addition to this, Jiangsu also has a huge river flow, which has played a significant role in both international trade and the domestic market. At the same time, just like Guangzhou Province, Jiangsu also relies on a highly developed economic center like Shanghai, which provides more job opportunities for Jiangsu. While understanding the development of these two cities, we realize that those inland provinces lack such opportunities, and therefore their economic development is slower. This is a problem worthy of people's attention.


